
import React, { createContext, useState, useContext, ReactNode } from 'react';

interface LanguageContextType {
  language: 'pt' | 'en';
  t: (key: string) => string;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    welcome: "Bem-vindo",
    description: "Um lugar para comprar produtos e ganhar cashback em Fan Tokens.",
    connectWallet: "Conectar Carteira",
    connected: "Conectado",
    stores: "Lojas",
    about: "Sobre",
    contact: "Contato",
    dashboard: "Meu Painel",
    logout: "Sair",
    login: "Entrar",
    register: "Cadastrar",
    success: "Sucesso",
    error: "Erro",
    loading: "Carregando...",
    cancel: "Cancelar",
    save: "Salvar",
    edit: "Editar",
    delete: "Excluir",
    create: "Criar",
    update: "Atualizar",
    proceed: "Prosseguir",
    close: "Fechar",
    confirm: "Confirmar",
    back: "Voltar",
    next: "Próximo",
    submit: "Enviar",
    search: "Buscar",
    filter: "Filtrar",
    all: "Todos",
    home: "Início",
    partnerStores: "Lojas Parceiras",
    storesDescription: "Compre nas lojas parceiras e ganhe cashback em Fan Tokens.",
    filterByCountry: "Filtrar por País",
    filterByCategory: "Filtrar por Categoria",
    filterByClub: "Filtrar por Clube",
    allCountries: "Todos os Países",
    allCategories: "Todas as Categorias",
    allClubs: "Todos os Clubes",
    category: "Categoria",
    country: "País",
    club: "Clube",
    cashback: "Cashback",
    buyNow: "Comprar Agora",
    noStoresFound: "Nenhuma loja encontrada",
    adjustFilters: "Tente ajustar os filtros para ver mais lojas.",
    errorFetchingStores: "Erro ao buscar lojas. Por favor, tente novamente.",
    selectToken: "Selecionar Token",
    selectTokenDescription: "Escolha o Fan Token que você deseja utilizar para esta compra.",
    bonusInfo: "Informações de bônus",
    bonusExplanation: "Ganhe bônus adicionais usando Fan Tokens relacionados ao clube parceiro da loja.",
    selectedToken: "Token Selecionado",
    bonusDetails: "Detalhes do Bônus",
    storeBonus: "Bônus da Loja",
    holdingBonus: "Bônus por Posse",
    bonus: "bônus",
    conversionNotice: "Os tokens serão convertidos no momento da confirmação da compra de acordo com a taxa.",
    redirectNotice: "Você será redirecionado para o site da loja para finalizar sua compra.",
    redirectWarningTitle: "Aviso de Redirecionamento",
    redirectWarning: "Você está sendo redirecionado para um site externo. Certifique-se de completar sua compra para ganhar seu cashback em Fan Tokens.",
    redirectingIn: "Redirecionando em",
    seconds: "segundos",
    fanTokens: "Fan Tokens",
    fanTokensDescription: "Lista de Fan Tokens disponíveis na plataforma.",
    createFanToken: "Criar Fan Token",
    editFanToken: "Editar Fan Token",
    updateFanToken: "Atualizar Fan Token",
    deleteFanToken: "Excluir Fan Token",
    fanTokenFormDescription: "Preencha os detalhes do Fan Token abaixo.",
    fanTokenNamePlaceholder: "Nome do Fan Token",
    fanTokenSlugPlaceholder: "slug-do-token",
    imageUrl: "URL da imagem",
    imagePreview: "Pré-visualização",
    preview: "Pré-visualização",
    noFanTokens: "Nenhum Fan Token encontrado",
    fanTokenSaved: "Fan Token salvo com sucesso!",
    fanTokenDeleted: "Fan Token excluído com sucesso!",
    errorFetchingFanTokens: "Erro ao buscar Fan Tokens. Por favor, tente novamente.",
    errorSavingFanToken: "Erro ao salvar Fan Token. Por favor, tente novamente.",
    errorDeletingFanToken: "Erro ao excluir Fan Token. Por favor, tente novamente.",
    deleteFanTokenConfirmation: "Tem certeza que deseja excluir este Fan Token",
    name: "Nome",
    slug: "Slug",
    amount: "Quantidade",
    fanTokenSlugHelp: "Use apenas letras minúsculas, números e hífens",
    fanTokenRequired: "Este campo é obrigatório",
    noTokensAvailable: "Nenhum Fan Token disponível no momento",
    userDashboard: "Painel do Usuário",
    totalCashback: "Cashback Total",
    accumulatedInWallet: "Acumulado na sua carteira",
    transactions: "Transações",
    confirmed: "Confirmadas",
    pending: "Pendentes",
    pendingCashback: "Cashback Pendente",
    inTransactions: "Em {count} transações",
    noTransactionsFound: "Nenhuma transação encontrada",
    noStoresPurchases: "Você ainda não fez compras em nenhuma loja parceira.",
    exploreStores: "Explorar Lojas",
    dataRefreshed: "Dados atualizados com sucesso!",
    refreshWalletData: "Atualizar dados da carteira",
    refreshingData: "Atualizando dados...",
    yourFanTokens: "Seus Fan Tokens",
    yourPurchaseNFTs: "Seus NFTs de Compra",
    viewPartnerStores: "Ver Lojas Parceiras",
    loginRequired: "Login Necessário",
    pleaseLoginToAccessDashboard: "Por favor, faça login para acessar seu painel.",
    goToLogin: "Ir para Login",
    heroTitle: "Transforme suas compras em",
    heroTitleHighlight: "Fan Tokens",
    heroTitleEnd: "com cashback",
    heroDescription: "Faça compras em lojas parceiras e receba cashback em Fan Tokens. Apoie seu time favorito enquanto economiza!",
    viewStores: "Ver Lojas",
    viewDashboard: "Ver Meu Painel",
    howItWorks: "Como Funciona",
    step1Title: "Conecte sua Carteira",
    step1Description: "Conecte sua carteira digital para começar a ganhar Fan Tokens como cashback.",
    step2Title: "Compre em Lojas Parceiras",
    step2Description: "Faça suas compras nas lojas parceiras do Back2Fan e ganhe cashback em Fan Tokens.",
    step3Title: "Receba Fan Tokens",
    step3Description: "Receba automaticamente Fan Tokens como cashback pelas suas compras.",
    featuredStores: "Lojas em Destaque",
    featuredStoresDescription: "Confira algumas de nossas lojas parceiras e os cashbacks oferecidos.",
    viewAllStores: "Ver Todas as Lojas",
    ctaTitle: "Comece a Ganhar Fan Tokens Hoje!",
    ctaDescription: "Conecte sua carteira e comece a acumular Fan Tokens enquanto faz suas compras online.",
    bonusSystem: "Sistema de Bônus",
    bonusSystemExplanation: "Ganhe bônus extras de cashback baseados no seu nível de posse de Fan Tokens.",
    tier1Name: "Nível Básico",
    tier1Description: "Ganhe 1% extra de cashback ao usar qualquer Fan Token em nossas lojas parceiras.",
    tier2Name: "Nível Prata",
    tier2Description: "Ganhe 3% extra de cashback quando usar Fan Tokens relacionados ao clube da loja.",
    tier3Name: "Nível Ouro",
    tier3Description: "Ganhe 5% extra de cashback para usuários que possuem mais de 100 Fan Tokens de um clube.",
    bonusExample: "Exemplo: Uma compra de R$100 com 5% de cashback base + 3% de bônus = R$8 em Fan Tokens.",
    about: "Sobre",
    termsOfUse: "Termos de Uso",
    privacyPolicy: "Política de Privacidade",
    faq: "FAQ",
    allRightsReserved: "Todos os direitos reservados.",
    contact: "Entre em contato",
    wallet: "Carteira",
    wallet: "Wallet",
    welcomeToBack2Fan: "Bem-vindo ao Back2Fan",
    connectWalletToEnter: "Conecte sua carteira para entrar no mundo dos Fan Tokens e cashback.",
    metamaskConnectWallet: "Conectar com MetaMask",
    walletConnected: "Carteira Conectada",
    termsAndPrivacyNotice: "Ao conectar sua carteira, você concorda com nossos Termos de Uso e Política de Privacidade.",
    continueToRegistration: "Continuar para Registro",
    firstName: "Primeiro Nome",
    lastName: "Último Nome",
    createing: "Criando...",
    createyour: "Crie sua conta",
    email: "Email",
    yourEmail: "Seu Email",
    waalletWillbeLinked: "Sua conta será vinculada a este endereço:",
    checkingWalletRegistration: "Verificando registro da carteira...",
    processingLogin: "Processando login...",
    accountChanged: "Conta alterada",
    holdings: "Qtde",
    bonusTier: "Nível de Bônus",
  },
  en: {
    welcome: "Welcome",
    description: "A place to buy products and earn cashback in Fan Tokens.",
    connectWallet: "Connect Wallet",
    connected: "Connected",
    stores: "Stores",
    about: "About",
    contact: "Contact",
    dashboard: "My Dashboard",
    logout: "Logout",
    login: "Login",
    register: "Register",
    success: "Success",
    error: "Error",
    loading: "Loading...",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    create: "Create",
    update: "Update",
    proceed: "Proceed",
    close: "Close",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    submit: "Submit",
    search: "Search",
    filter: "Filter",
    all: "All",
    home: "Home",
    partnerStores: "Partner Stores",
    storesDescription: "Shop at partner stores and earn cashback in Fan Tokens.",
    filterByCountry: "Filter by Country",
    filterByCategory: "Filter by Category",
    filterByClub: "Filter by Club",
    allCountries: "All Countries",
    allCategories: "All Categories",
    allClubs: "All Clubs",
    category: "Category",
    country: "Country",
    club: "Club",
    cashback: "Cashback",
    buyNow: "Buy Now",
    noStoresFound: "No stores found",
    adjustFilters: "Try adjusting your filters to see more stores.",
    errorFetchingStores: "Error fetching stores. Please try again.",
    selectToken: "Select Token",
    selectTokenDescription: "Choose the Fan Token you want to use for this purchase.",
    bonusInfo: "Bonus info",
    bonusExplanation: "Earn additional bonuses by using Fan Tokens related to the store's partner club.",
    selectedToken: "Selected Token",
    bonusDetails: "Bonus Details",
    storeBonus: "Store Bonus",
    holdingBonus: "Holding Bonus",
    bonus: "bonus",
    conversionNotice: "Tokens will be converted at the time of purchase according to the current rate.",
    redirectNotice: "You will be redirected to the store's website to complete your purchase.",
    redirectWarningTitle: "Redirection Warning",
    redirectWarning: "You're being redirected to an external website. Make sure to complete your purchase to earn your Fan Token cashback.",
    redirectingIn: "Redirecting in",
    seconds: "seconds",
    amount: "Amount",
    fanTokens: "Fan Tokens",
    fanTokensDescription: "List of Fan Tokens available on the platform.",
    createFanToken: "Create Fan Token",
    editFanToken: "Edit Fan Token",
    updateFanToken: "Update Fan Token",
    deleteFanToken: "Delete Fan Token",
    fanTokenFormDescription: "Fill in the Fan Token details below.",
    fanTokenNamePlaceholder: "Fan Token Name",
    fanTokenSlugPlaceholder: "token-slug",
    imageUrl: "Image URL",
    imagePreview: "Preview",
    preview: "Preview",
    noFanTokens: "No Fan Tokens found",
    fanTokenSaved: "Fan Token saved successfully!",
    fanTokenDeleted: "Fan Token deleted successfully!",
    errorFetchingFanTokens: "Error fetching Fan Tokens. Please try again.",
    errorSavingFanToken: "Error saving Fan Token. Please try again.",
    errorDeletingFanToken: "Error deleting Fan Token. Please try again.",
    deleteFanTokenConfirmation: "Are you sure you want to delete this Fan Token",
    name: "Name",
    slug: "Slug",
    fanTokenSlugHelp: "Use only lowercase letters, numbers, and hyphens",
    fanTokenRequired: "This field is required",
    noTokensAvailable: "No Fan Tokens available at this time",
    userDashboard: "User Dashboard",
    totalCashback: "Total Cashback",
    accumulatedInWallet: "Accumulated in your wallet",
    transactions: "Transactions",
    confirmed: "Confirmed",
    pending: "Pending",
    pendingCashback: "Pending Cashback",
    inTransactions: "In {count} transactions",
    noTransactionsFound: "No transactions found",
    noStoresPurchases: "You haven't made any purchases at partner stores yet.",
    exploreStores: "Explore Stores",
    dataRefreshed: "Data refreshed successfully!",
    refreshWalletData: "Refresh wallet data",
    refreshingData: "Refreshing data...",
    yourFanTokens: "Your Fan Tokens",
    yourPurchaseNFTs: "Your Purchase NFTs",
    viewPartnerStores: "View Partner Stores",
    loginRequired: "Login Required",
    pleaseLoginToAccessDashboard: "Please login to access your dashboard.",
    goToLogin: "Go to Login",
    heroTitle: "Transform your purchases into",
    heroTitleHighlight: "Fan Tokens",
    heroTitleEnd: "with cashback",
    heroDescription: "Shop at partner stores and receive cashback in Fan Tokens. Support your favorite team while saving!",
    viewStores: "View Stores",
    viewDashboard: "View My Dashboard",
    howItWorks: "How It Works",
    step1Title: "Connect Your Wallet",
    step1Description: "Connect your digital wallet to start earning Fan Tokens as cashback.",
    step2Title: "Shop at Partner Stores",
    step2Description: "Make purchases at Back2Fan partner stores and earn cashback in Fan Tokens.",
    step3Title: "Receive Fan Tokens",
    step3Description: "Automatically receive Fan Tokens as cashback for your purchases.",
    featuredStores: "Featured Stores",
    featuredStoresDescription: "Check out some of our partner stores and their cashback offers.",
    viewAllStores: "View All Stores",
    ctaTitle: "Start Earning Fan Tokens Today!",
    bonusSystem: "Bonus System",
    bonusSystemExplanation: "Earn extra cashback bonuses based on your Fan Token holding level.",
    tier1Name: "Basic Tier",
    tier1Description: "Earn 1% extra cashback when using any Fan Token at our partner stores.",
    tier2Name: "Silver Tier",
    tier2Description: "Earn 3% extra cashback when using Fan Tokens related to the store's club.",
    tier3Name: "Gold Tier",
    tier3Description: "Earn 5% extra cashback for users who hold more than 100 Fan Tokens of a club.",
    bonusExample: "Example: A $100 purchase with 5% base cashback + 3% bonus = $8 in Fan Tokens.",
    about: "About",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    faq: "FAQ",
    allRightsReserved: "All rights reserved.",
    contact: "Contact Us",
    wallet: "Wallet",
    welcomeToBack2Fan: "Welcome to Back2Fan",
    connectWalletToEnter: "Connect your wallet to enter the world of Fan Tokens and cashback.",
    metamaskConnectWallet: "Connect with MetaMask",
    walletConnected: "Wallet Connected",
    termsAndPrivacyNotice: "By connecting your wallet, you agree to our Terms of Use and Privacy Policy.",
    continueToRegistration: "Continue to Registration",
    firstName: "First Name",
    lastName: "Last Name",
    createing: "Creating...",
    createyour: "Create your account",
    email: "Email",
    yourEmail: "Your Email",
    waalletWillbeLinked: "Your account will be linked to this address:",
    checkingWalletRegistration: "Checking wallet registration...",
    processingLogin: "Processing login...",
    accountChanged: "Account changed",
    holdings: "Qty",
    bonusTier: "Bonus Tier",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<'pt' | 'en'>('pt');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'pt' ? 'en' : 'pt');
  };

  const t = (key: string) => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
